@echo off
echo === IMPORTANDO CONFIGURACOES ===
call .env.bat

:: === DEFINICOES DE NOMES DO PROJETO ===
set "JDBC_CLASS=org.hsqldb.jdbcDriver"
set "MODULE_NAME=br.inatel.dm110.hsqldb"
set "DRIVER_NAME=HSQLDBDriver"
set "DB_NAME_ORDER=order-dm110.db"
set "DB_NAME_AUDIT=audit-dm110.db"
set "USER_DB_ORDER=orderdm110"
set "PASS_DB_ORDER=senhadm110"
set "USER_DB_AUDIT=auditdm110"
set "PASS_DB_AUDIT=senhadm110"
set "DS_ORDER_NAME=OrderDS"
set "DS_AUDIT_NAME=AuditDS"
set "JNDI_ORDER=java:/OrderDS"
set "JNDI_AUDIT=java:/AuditDS"


:: === CRIANDO CONNECTION STRINGS ===
set "CONN_URL_ORDER=jdbc:hsqldb:file:%PATH_HSQLDB%\\%DB_NAME_ORDER%"
set "CONN_URL_AUDIT=jdbc:hsqldb:file:%PATH_HSQLDB%\\%DB_NAME_AUDIT%"

echo .
echo === INICIANDO O WILDFLY EM NOVA JANELA ===
start "" %WILDFLY_HOME%\bin\standalone.bat -c=standalone-full.xml
pause

echo === CRIANDO O BANCO DE DADOS ORDER NO HSQLDB ===
echo .
echo = Execute a query abaixo no banco de dados Orders criado:
echo .
echo CREATE TABLE ORDERS (
echo     ORDERCODE VARCHAR(10) NOT NULL,
echo     PRODUCTCODE VARCHAR(10) NOT NULL,
echo     CPF VARCHAR(11) NOT NULL,
echo     AMOUNT FLOAT NOT NULL,
echo     DATEORDER VARCHAR(15),
echo     ORDERVALUE VARCHAR(10),
echo     PRIMARY KEY (ORDERCODE)
echo );
call java -jar %DRIVER_PATH% --url %CONN_URL_ORDER% --user %USER_DB_ORDER% --password %PASS_DB_ORDER%
pause

echo === CRIANDO O BANCO DE DADOS AUDIT NO HSQLDB ===
echo .
echo = Execute a query abaixo no banco de dados Audito criado:
echo .
echo CREATE TABLE AUDIT (
echo    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
echo    RECORDCODE VARCHAR(50),
echo    OPERATION VARCHAR(20),
echo    TIMESTAMP TIMESTAMP
echo );
call java -jar %DRIVER_PATH% --url %CONN_URL_AUDIT% --user %USER_DB_AUDIT% --password %PASS_DB_AUDIT%
pause

echo === ADICIONANDO O DRIVER HSQLDB NO WILDFLY ===
call    %JBOSS_CLI% --connect --command="module add --name=%MODULE_NAME% --dependencies=javax.transaction.api --export-dependencies=javax.api --resources=%DRIVER_PATH%"
call    %JBOSS_CLI% --connect --command="/subsystem=datasources/jdbc-driver=%DRIVER_NAME%:add(driver-name=%DRIVER_NAME%,driver-module-name=%MODULE_NAME%,driver-class-name=%JDBC_CLASS%)"

echo === CRIANDO OS DATASOURCES ===
call    %JBOSS_CLI% --connect --command="data-source add --name=%DS_ORDER_NAME% --jndi-name=%JNDI_ORDER% --driver-name=%DRIVER_NAME% --connection-url=%CONN_URL_ORDER% --user-name=%USER_DB_ORDER% --password=%PASS_DB_ORDER%"
call    %JBOSS_CLI% --connect --command="data-source add --name=%DS_AUDIT_NAME% --jndi-name=%JNDI_AUDIT% --driver-name=%DRIVER_NAME% --connection-url=%CONN_URL_AUDIT% --user-name=%USER_DB_AUDIT% --password=%PASS_DB_AUDIT%"


echo === CRIANDO A FILA DE AUDITORIA ===
call %JBOSS_CLI% --connect --command="jms-queue add --queue-address=auditQueue --durable=true --entries=[\"java:/jms/queue/auditQueue\"]"

echo === FAZENDO O DEPLOY DO EAR ===
call %JBOSS_CLI% --connect --command="deploy %EAR_FILE_PATH%"
echo .
echo === CONFIG FINALIZADA ===
pause