-- tabela de Pedidos

CREATE TABLE ORDERS (
  ORDERCODE VARCHAR(10) NOT NULL,
  PRODUCTCODE VARCHAR(10) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  AMOUNT FLOAT NOT NULL,
  DATEORDER VARCHAR(15),
  ORDERVALUE VARCHAR(10),
  PRIMARY KEY (ORDERCODE)
);

-- tabela de auditoria



